# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3966b17d28a83066354fdd3fab8fc727"
name = "image-handle-app"
handle = "image-handle-app"
application_url = "https://shopify-takaokaya-image-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "179sample.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_metaobject_definitions,read_metaobjects,read_products,read_themes,write_files,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://shopify-takaokaya-image-app.onrender.com/auth/callback",
  "https://shopify-takaokaya-image-app.onrender.com/auth/shopify/callback",
  "https://shopify-takaokaya-image-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
