export const Patterns = [
  // 木綿・むら染め・無地
  {
    designNo: 21,
    no: "21",
    type: "cotton-plain",
    value: "砧青磁（きぬたせいじ）",
    name: "砧青磁",
    kana: "きぬたせいじ",
    english: "Kinutaseiji",
    colorName: "スカイブルー",
  },
  {
    designNo: 23,
    no: "23",
    type: "cotton-plain",
    value: "藤紫（ふじむらさき）",
    name: "藤紫",
    kana: "ふじむらさき",
    english: "Fujimurasaki",
    colorName: "グレープ",
  },
  {
    designNo: 24,
    no: "24",
    type: "cotton-plain",
    value: "黄唐茶（きからちゃ）",
    name: "黄唐茶",
    kana: "きからちゃ",
    english: "Kikaracha",
    colorName: "ブラウン",
  },
  {
    designNo: 25,
    no: "25",
    type: "cotton-plain",
    value: "勿忘草色（わすれなぐさいろ）",
    name: "勿忘草色",
    kana: "わすれなぐさいろ",
    english: "Wasurenagusairo",
    colorName: "マリンブルー",
  },
  {
    designNo: 26,
    no: "26",
    type: "cotton-plain",
    value: "裏葉色（うらはいろ）",
    name: "裏葉色",
    kana: "うらはいろ",
    english: "Urahairo",
    colorName: "セラドングリーン",
  },
  {
    designNo: 27,
    no: "27",
    type: "cotton-plain",
    value: "里桜（さとざくら）",
    name: "里桜",
    kana: "さとざくら",
    english: "Satozakura",
    colorName: "ピンク",
  },
  {
    designNo: 28,
    no: "28",
    type: "cotton-plain",
    value: "金木犀（きんもくせい）",
    name: "金木犀",
    kana: "きんもくせい",
    english: "Kinmokusei",
    colorName: "イエロー",
  },
  {
    designNo: 29,
    no: "29",
    type: "cotton-plain",
    value: "鳥の子（とりのこ）",
    name: "鳥の子",
    kana: "とりのこ",
    english: "Torinoko",
    colorName: "ベージュ",
  },
  {
    designNo: 30,
    no: "30",
    type: "cotton-plain",
    value: "紙屋紙（かみやがみ）",
    name: "紙屋紙",
    kana: "かみやがみ",
    english: "Kamiyagami",
    colorName: "グレー",
  },
  {
    designNo: 31,
    no: "31",
    type: "cotton-plain",
    value: "千草（ちぐさ）",
    name: "千草",
    kana: "ちぐさ",
    english: "Chigusa",
    colorName: "ネイビーブルー",
  },
  {
    designNo: 32,
    no: "32",
    type: "cotton-plain",
    value: "翁苔（おきなごけ）",
    name: "翁苔",
    kana: "おきなごけ",
    english: "Okinagoke",
    colorName: "モスグリーン",
  },
  {
    designNo: 33,
    no: "33",
    type: "cotton-plain",
    value: "蘇芳（すおう）",
    name: "蘇芳",
    kana: "すおう",
    english: "Suou",
    colorName: "ワイン",
  },
  {
    designNo: 34,
    no: "34",
    type: "cotton-plain",
    value: "京鹿子（きょうかのこ）",
    name: "京鹿子",
    kana: "きょうかのこ",
    english: "Kyokanoko",
    colorName: "レッド",
  },
  {
    designNo: 35,
    no: "35",
    type: "cotton-plain",
    value: "薔薇（しょうび）",
    name: "薔薇",
    kana: "しょうび",
    english: "Shoubi",
    colorName: "ローズピンク",
  },
  {
    designNo: 36,
    no: "36",
    type: "cotton-plain",
    value: "洒落柿（しゃれがき）",
    name: "洒落柿",
    kana: "しゃれがき",
    english: "Sharegaki",
    colorName: "オレンジ",
  },
  {
    designNo: 37,
    no: "37",
    type: "cotton-plain",
    value: "御納戸（おなんど）",
    name: "御納戸",
    kana: "おなんど",
    english: "Onando",
    colorName: "インディゴ",
  },
  {
    designNo: 38,
    no: "38",
    type: "cotton-plain",
    value: "檜皮（ひはだ）",
    name: "檜皮",
    kana: "ひはだ",
    english: "Hihada",
    colorName: "セピア",
  },
  {
    designNo: 40,
    no: "40",
    type: "cotton-plain",
    value: "躑躅色（つつじいろ）",
    name: "躑躅色",
    kana: "つつじいろ",
    english: "Tsutsujiro",
    colorName: "ビビッドピンク",
  },
  {
    designNo: 41,
    no: "41",
    type: "cotton-plain",
    value: "菜の花（なのはな）",
    name: "菜の花",
    kana: "なのはな",
    english: "Nanohana",
    colorName: "ブリリアントイエロー",
  },
  {
    designNo: 42,
    no: "42",
    type: "cotton-plain",
    value: "萌黄（もえぎ）",
    name: "萌黄",
    kana: "もえぎ",
    english: "Moegi",
    colorName: "フレッシュグリーン",
  },
  {
    designNo: 43,
    no: "43",
    type: "cotton-plain",
    value: "支子（くちなし）",
    name: "支子",
    kana: "くちなし",
    english: "Kuchinashi",
    colorName: "タンジェリン",
  },
  {
    designNo: 44,
    no: "44",
    type: "cotton-plain",
    value: "藍玉（らんぎょく）",
    name: "藍玉",
    kana: "らんぎょく",
    english: "Rangyoku",
    colorName: "アクアブルー",
  },
  {
    designNo: 45,
    no: "45",
    type: "cotton-plain",
    value: "褐色（かちいろ）",
    name: "褐色",
    kana: "かちいろ",
    english: "Kachiiro",
    colorName: "カチイロ",
  },

  // 木綿・むら染め・和柄
  {
    designNo: 1000,
    no: "1000",
    type: "cotton-wa",
    value: "あられ・紫",
    name: "あられ・紫",
    english: "Arare Murasaki",
  },
  {
    designNo: 1001,
    no: "1001",
    type: "cotton-wa",
    value: "あられ・緑",
    name: "あられ・緑",
    english: "Arare Midori",
  },
  {
    designNo: 1002,
    no: "1002",
    type: "cotton-wa",
    value: "あられ・黒",
    name: "あられ・黒",
    english: "Arare Kuro",
  },
  {
    designNo: 1003,
    no: "1003",
    type: "cotton-wa",
    value: "あられ・ピンク",
    name: "あられ・ピンク",
    english: "Arare Pink",
  },
  {
    designNo: 1004,
    no: "1004",
    type: "cotton-wa",
    value: "あられ・赤",
    name: "あられ・赤",
    english: "Arare Aka",
  },
  {
    designNo: 1005,
    no: "1005",
    type: "cotton-wa",
    value: "三色あられ",
    name: "三色あられ",
    english: "Sanshoku Arare",
  },
  {
    designNo: 1009,
    no: "1009",
    type: "cotton-wa",
    value: "縞きなり",
    name: "縞きなり",
    english: "Shima Kinari",
  },
  {
    designNo: 1010,
    no: "1010",
    type: "cotton-wa",
    value: "縞みどり",
    name: "縞みどり",
    english: "Shima Midori",
  },
  {
    designNo: 1011,
    no: "1011",
    type: "cotton-wa",
    value: "縞あお",
    name: "縞あお",
    english: "Shima Ao",
  },
  {
    designNo: 1006,
    no: "1006",
    type: "cotton-wa",
    value: "絞りピンク",
    name: "絞りピンク",
    english: "Shibori Pink",
  },
  {
    designNo: 1008,
    no: "1008",
    type: "cotton-wa",
    value: "絞り緑",
    name: "絞り緑",
    english: "Shibori Midori",
  },
  {
    designNo: 1007,
    no: "1007",
    type: "cotton-wa",
    value: "絞り黒",
    name: "絞り黒",
    english: "Shibori Kuro",
  },
  {
    designNo: 1021,
    no: "1021",
    type: "cotton-wa",
    value: "星七宝紺",
    name: "星七宝紺",
    english: "Hoshi Shippo Kon",
  },
  {
    designNo: 1022,
    no: "1022",
    type: "cotton-wa",
    value: "星七宝赤",
    name: "星七宝赤",
    english: "Hoshi Shippo Aka",
  },
  {
    designNo: 1101,
    no: "1101",
    type: "cotton-wa",
    value: "市松・あか",
    name: "市松・あか",
    english: "Ichimatsu Aka",
  },
  {
    designNo: 1102,
    no: "1102",
    type: "cotton-wa",
    value: "市松・みどり",
    name: "市松・みどり",
    english: "Ichimatsu Midori",
  },

  // 北欧調
  {
    designNo: 2001,
    no: "2001",
    type: "cotton-nordic",
    value: "メイズ・ブラック",
    name: "メイズ・ブラック",
    english: "Maze Black",
  },
  {
    designNo: 2002,
    no: "2002",
    type: "cotton-nordic",
    value: "メイズ・ホワイト",
    name: "メイズ・ホワイト",
    english: "Maze White",
  },
  {
    designNo: 2003,
    no: "2003",
    type: "cotton-nordic",
    value: "メイズ・イエロー",
    name: "メイズ・イエロー",
    english: "Maze Yellow",
  },
  {
    designNo: 2010,
    no: "2010",
    type: "cotton-nordic",
    value: "マーブルブラック",
    name: "マーブルブラック",
    english: "Marble Black",
  },
  /*
  {
    designNo: 2020,
    no: "2020",
    type: "cotton-nordic",
    value: "すぐりブラック",
    name: "すぐりブラック",
    english: "Suguri Black",
  },
  */
  {
    designNo: 2030,
    no: "2030",
    type: "cotton-nordic",
    value: "フローラルグリーン",
    name: "フローラルグリーン",
    english: "Floral Green",
  },
  {
    designNo: 2031,
    no: "2031",
    type: "cotton-nordic",
    value: "フローラルピンク",
    name: "フローラルピンク",
    english: "Floral Pink",
  },
  {
    designNo: 2040,
    no: "2040",
    type: "cotton-nordic",
    value: "ブーケブルー",
    name: "ブーケブルー",
    english: "Bouquet Blue",
  },
  {
    designNo: 2041,
    no: "2041",
    type: "cotton-nordic",
    value: "ブーケレッド",
    name: "ブーケレッド",
    english: "Bouquet Red",
  },
  /*
  {
    designNo: 2050,
    no: "2050",
    type: "cotton-nordic",
    value: "宝石・ミズ",
    name: "宝石・ミズ",
    english: "Jewel Mizu",
  },
  */
  {
    designNo: 2060,
    no: "2060",
    type: "cotton-nordic",
    value: "しゃぼん・はる",
    name: "しゃぼん・はる",
    english: "Shabon Haru",
  },
  {
    designNo: 2061,
    no: "2061",
    type: "cotton-nordic",
    value: "しゃぼん・ふゆ",
    name: "しゃぼん・ふゆ",
    english: "Shabon Fuyu",
  },
  {
    designNo: 2070,
    no: "2070",
    type: "cotton-nordic",
    value: "ツリー・おはじき",
    name: "ツリー・おはじき",
    english: "Tree Ohajiki",
  },
  {
    designNo: 2071,
    no: "2071",
    type: "cotton-nordic",
    value: "ツリー・てまり",
    name: "ツリー・てまり",
    english: "Tree Temari",
  },

  // 麻
  {
    desinNo: 10003,
    no: "003",
    type: "asa",
    value: "苗色",
    name: "苗色",
    kana: "なえいろ",
    colorName: "グリーン",
  },
  {
    designNo: 10005,
    no: "005",
    type: "asa",
    value: "浅縹",
    name: "浅縹",
    kana: "あさはなだ",
    colorName: "ブルー",
  },
  {
    designNo: 10006,
    no: "006",
    type: "asa",
    value: "青鈍",
    name: "青鈍",
    kana: "あおにび",
    colorName: "グレー",
  },
  {
    designNo: 10007,
    no: "007",
    type: "asa",
    value: "鳥の子",
    name: "鳥の子",
    kana: "とりのこ",
    colorName: "ナチュラル",
  },
  {
    designNo: 10008,
    no: "008",
    type: "asa",
    value: "葩",
    name: "葩",
    kana: "はなびらもち",
    colorName: "ピンク",
  },
  {
    designNo: 10009,
    no: "009",
    type: "asa",
    value: "橘",
    name: "橘",
    kana: "たちばな",
    colorName: "イエロー",
  },
  {
    designNo: 10010,
    no: "010",
    type: "asa",
    value: "石竹",
    name: "石竹",
    kana: "せきちく",
    colorName: "オレンジ",
  },
  {
    designNo: 10015,
    no: "015",
    type: "asa",
    value: "丁字茶",
    name: "丁字茶",
    kana: "ちょうじちゃ",
    colorName: "ブラウン",
  },
  {
    designNo: 10016,
    no: "016",
    type: "asa",
    value: "空色",
    name: "空色",
    kana: "そらいろ",
    colorName: "ネイビーブルー",
  },
  {
    designNo: 10017,
    no: "017",
    type: "asa",
    value: "墨",
    name: "墨",
    kana: "すみ",
    colorName: "ブラック",
  },
  {
    designNo: 10018,
    no: "018",
    type: "asa",
    value: "銹絵",
    name: "銹絵",
    kana: "さびえ",
    colorName: "ダークブラウン",
  },
  {
    designNo: 10020,
    no: "020",
    type: "asa",
    value: "碾茶",
    name: "碾茶",
    kana: "てんちゃ",
    colorName: "モスグリーン",
  },
  {
    designNo: 10021,
    no: "021",
    type: "asa",
    value: "印度藍",
    name: "印度藍",
    kana: "いんどあい",
    colorName: "インディゴ",
  },
  {
    designNo: 10022,
    no: "022",
    type: "asa",
    value: "躑躅色",
    name: "躑躅色",
    kana: "つつじいろ",
    colorName: "ビビッドピンク",
  },
  {
    designNo: 10023,
    no: "023",
    type: "asa",
    value: "藤紫",
    name: "藤紫",
    kana: "ふじむらさき",
    colorName: "パープル",
  },
];
